trigger: none
 
variables:
  serviceConnection: 'devops_uami'
  resourceGroupName: 'GSWA'
  functionAppName: 'gswardc'
  workingDirectory: '$(System.DefaultWorkingDirectory)/rdf_delta_consumer'
 
stages:
- stage: Deploy

  jobs:
    - job: zipdeploy
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: ArchiveFiles@2
          inputs:
            includeRootFolder: false
            rootFolderOrFile: $(workingDirectory)
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/app.zip
            replaceExistingArchive: true

        - task: AzureFunctionApp@2
          inputs:
            azureSubscription: ${{ variables.serviceConnection }}
            appType: functionAppLinux
            appName: ${{ variables.functionAppName }}
            package: $(Build.ArtifactStagingDirectory)/app.zip
            deployToSlotOrASE: true  
            resourceGroupName: ${{ variables.resourceGroupName }}
            deploymentMethod: 'zipDeploy'
