trigger: none
 
variables:
  serviceConnection: 'devops_uami'
  resourceGroupName: 'GSWA'
  functionAppName: 'gswasdt'
  workingDirectory: '$(System.DefaultWorkingDirectory)/db_trigger'
 
stages:
- stage: Deploy

  jobs:
    - job: zipdeploy
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: 3.12

        - bash: |
            pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
          workingDirectory: $(workingDirectory)

        - task: ArchiveFiles@2
          inputs:
            includeRootFolder: false
            rootFolderOrFile: $(workingDirectory)
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/app.zip
            replaceExistingArchive: true

        - task: AzureFunctionApp@2
          inputs:
            azureSubscription: ${{ variables.serviceConnection }}
            appType: functionAppLinux
            appName: ${{ variables.functionAppName }}
            package: $(Build.ArtifactStagingDirectory)/app.zip
            deployToSlotOrASE: true  
            resourceGroupName: ${{ variables.resourceGroupName }}
            deploymentMethod: 'zipDeploy'
