trigger: none
 
variables:
  serviceConnection: 'devops_uami'
  resourceGroupName: 'GSWA'
  functionAppName: 'gswasdt'
  workingDirectory: '$(System.DefaultWorkingDirectory)/db_trigger'
 
stages:
- stage: Build_and_Deploy
  displayName: Build and Deploy Stage
 
  jobs:
  - job: zipdeploy
    displayName: Build App
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: ArchiveFiles@2
        inputs:
          includeRootFolder: false
          rootFolderOrFile: $(workingDirectory)
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/app.zip
          replaceExistingArchive: true

      - task: AzureFunctionApp@2
        displayName: Deploy Function App
        inputs:
          azureSubscription: ${{ variables.serviceConnection }}
          appType: functionAppLinux
          appName: ${{ variables.functionAppName }}
          package: $(Build.ArtifactStagingDirectory)/app.zip
          deployToSlotOrASE: true  
          resourceGroupName: ${{ variables.resourceGroupName }}
          deploymentMethod: 'zipDeploy'
