# https://taskfile.dev

version: '3'

tasks:
  format:
    cmds:
      - uv run ruff format
      - uv run ruff check --fix

  code:
    cmds:
      - task: format

  consumer:
    cmd: uv run src/consumer.py