# https://taskfile.dev

version: "3"

tasks:
  default:
    cmd: task -a

  clean:
    desc: Clean the venv
    cmds:
      - rm -rf .venv
    ignore_error: true

  install:
    desc: Set up the venv and install python dependencies
    vars:
      PYTHON_VERSION:
        sh: cat .python-version | tr -d '\n'
    cmds:
      - task: clean
      - uv sync

  code:
    desc: Run the code linting and formatting
    cmds:
      - uv tool run ruff format
      - uv tool run ruff check --fix

  dev:
    desc: Run the function app in dev mode
    cmds:
      - uv run func start -p 7072

  test:
    desc: Run the tests
    cmd: uv run pytest
