# https://taskfile.dev

version: "3"

tasks:
  default:
    cmd: task -a

  clean:
    desc: Clean the venv
    cmds:
      - rm -rf .venv
      - python -m venv .venv
    ignore_error: true

  install:
    desc: Set up the venv and install python dependencies
    cmds:
      - task: clean
      - .venv/bin/pip install -r requirements.txt
      - .venv/bin/pip install -r requirements-dev.txt

  code:
    desc: Run the code linting and formatting
    cmds:
      - .venv/bin/ruff format
      - .venv/bin/ruff check --fix

  dev:
    desc: Run the function app in dev mode
    cmds:
      - func start -p 7072

  test:
    desc: Run the tests
    cmd: .venv/bin/pytest

  load:
    desc: Load the data into the database
    cmds:
      - .venv/bin/python sb_producer.py rdf-delta main users.trig
      - .venv/bin/python sb_producer.py rdf-delta main catalogs.trig
