# https://taskfile.dev

version: "3"

tasks:
  default:
    cmd: task -a

  clean:
    desc: Clean the venv
    cmds:
      - rm -rf .venv
      - python -m venv .venv
    ignore_error: true

  install:
    desc: Set up the venv and install python dependencies
    cmds:
      - task: clean
      - .venv/bin/pip install -r requirements.txt
      - .venv/bin/pip install -r requirements-dev.txt

  code:
    desc: Run the code linting and formatting
    cmds:
      - .venv/bin/ruff format
      - .venv/bin/ruff check --fix

  dev:
    desc: Run in dev mode
    cmds:
      - func start -p 7073
